sudo: required
services:
  - docker

before_install:
  - docker build -t kamalpinnapureddy/fibonacci-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kamalpinnapureddy/fibonacci-test npm test

after_success:
  - docker build -t kamalpinnapureddy/multi-client ./client
  - docker build -t kamalpinnapureddy/multi-nginx ./nginx
  - docker build -t kamalpinnapureddy/multi-server ./server
  - docker build -t kamalpinnapureddy/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin

  - docker push kamalpinnapureddy/multi-client
  - docker push kamalpinnapureddy4/multi-nginx
  - docker push kamalpinnapureddy/multi-server
  - docker push kamalpinnapureddy/multi-client

  #Take images to docker


